apiVersion: deploy.hybridapp.io/v1alpha1
kind: Operator
metadata:
  name: simple
spec:
  core:
    deployable:
      enabled: true
  tools:
    assembler:
      enabled: true
    discoverer:
      enabled: false
      clustername: toronto
      clusternamespace: toronto-ns

