// +build !ignore_autogenerated

// Copyright 2019 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationAssemblerSpec) DeepCopyInto(out *ApplicationAssemblerSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationAssemblerSpec.
func (in *ApplicationAssemblerSpec) DeepCopy() *ApplicationAssemblerSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationAssemblerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreSpec) DeepCopyInto(out *CoreSpec) {
	*out = *in
	if in.DeployableOperatorSpec != nil {
		in, out := &in.DeployableOperatorSpec, &out.DeployableOperatorSpec
		*out = new(DeployableOperatorSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreSpec.
func (in *CoreSpec) DeepCopy() *CoreSpec {
	if in == nil {
		return nil
	}
	out := new(CoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployableOperatorSpec) DeepCopyInto(out *DeployableOperatorSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployableOperatorSpec.
func (in *DeployableOperatorSpec) DeepCopy() *DeployableOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(DeployableOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericContainerSpec) DeepCopyInto(out *GenericContainerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(v1.PullPolicy)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericContainerSpec.
func (in *GenericContainerSpec) DeepCopy() *GenericContainerSpec {
	if in == nil {
		return nil
	}
	out := new(GenericContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubConnectionConfig) DeepCopyInto(out *HubConnectionConfig) {
	*out = *in
	if in.KubeConfig != nil {
		in, out := &in.KubeConfig, &out.KubeConfig
		*out = new(string)
		**out = **in
	}
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubConnectionConfig.
func (in *HubConnectionConfig) DeepCopy() *HubConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(HubConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseSpec) DeepCopyInto(out *LicenseSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseSpec.
func (in *LicenseSpec) DeepCopy() *LicenseSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operator) DeepCopyInto(out *Operator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operator.
func (in *Operator) DeepCopy() *Operator {
	if in == nil {
		return nil
	}
	out := new(Operator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Operator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorList) DeepCopyInto(out *OperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Operator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorList.
func (in *OperatorList) DeepCopy() *OperatorList {
	if in == nil {
		return nil
	}
	out := new(OperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorSpec) DeepCopyInto(out *OperatorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.LicenseSpec != nil {
		in, out := &in.LicenseSpec, &out.LicenseSpec
		*out = new(LicenseSpec)
		**out = **in
	}
	if in.CoreSpec != nil {
		in, out := &in.CoreSpec, &out.CoreSpec
		*out = new(CoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolsSpec != nil {
		in, out := &in.ToolsSpec, &out.ToolsSpec
		*out = new(ToolsSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorSpec.
func (in *OperatorSpec) DeepCopy() *OperatorSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorStatus) DeepCopyInto(out *OperatorStatus) {
	*out = *in
	if in.ReplicaSetStatus != nil {
		in, out := &in.ReplicaSetStatus, &out.ReplicaSetStatus
		*out = new(appsv1.ReplicaSetStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorStatus.
func (in *OperatorStatus) DeepCopy() *OperatorStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceDiscovererSpec) DeepCopyInto(out *ResourceDiscovererSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.ClusterNamespace != nil {
		in, out := &in.ClusterNamespace, &out.ClusterNamespace
		*out = new(string)
		**out = **in
	}
	if in.HubConnectionConfig != nil {
		in, out := &in.HubConnectionConfig, &out.HubConnectionConfig
		*out = new(HubConnectionConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDiscovererSpec.
func (in *ResourceDiscovererSpec) DeepCopy() *ResourceDiscovererSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceDiscovererSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsSpec) DeepCopyInto(out *ToolsSpec) {
	*out = *in
	if in.ApplicationAssemblerSpec != nil {
		in, out := &in.ApplicationAssemblerSpec, &out.ApplicationAssemblerSpec
		*out = new(ApplicationAssemblerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceDiscovererSpec != nil {
		in, out := &in.ResourceDiscovererSpec, &out.ResourceDiscovererSpec
		*out = new(ResourceDiscovererSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsSpec.
func (in *ToolsSpec) DeepCopy() *ToolsSpec {
	if in == nil {
		return nil
	}
	out := new(ToolsSpec)
	in.DeepCopyInto(out)
	return out
}
